### ISSUE TITLE
SCSS - Set transition to mixin

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/timecontrol#70]
Example: 

``` scss
// mixin:
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
     -moz-border-radius: $radius;
      -ms-border-radius: $radius;
          border-radius: $radius;
}

// Usage
.box { @include border-radius(10px); }
```
